name: Build release binaries for tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - uses: actions/checkout@v2

      - name: Make release
        run: |
          make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'cmd/kubectl-cost/kubectl-cost-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in Krew index
        uses: rajatjindal/krew-release-bot@v0.0.38
        # see https://github.com/rajatjindal/krew-release-bot
        # and /.krew.yaml
