name: PR - build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - uses: actions/checkout@v2

      - name: Make build
        run: |
          make build

